version = 1

# Ensure DeepSource knows where tests live
test_patterns = [
  "tests/**",
]

exclude_patterns = [
  ".git/**",
  "venv/**",
  ".venv/**",
  "dist/**",
  "build/**",
  "**/__pycache__/**",
]

[[analyzers]]
name = "python"
enabled = true
runtime_version = "3.x.x"

[analyzers.meta]
max_line_length = 120

[transformers]
  [transformers.black]
    enabled = true
  [transformers.isort]
    enabled = true

[reports]
coverage = { tool = "coverage.py", path = "coverage.xml" }