version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./src/database:/app/src/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/dashboard/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  database:
    driver: local

