"""Add missing fields to Project, Client, and Plant models

Revision ID: 376b42db1ebc
Revises: 5ce1771dc573
Create Date: 2025-07-29 14:03:54.615144

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '376b42db1ebc'
down_revision = '5ce1771dc573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=200), nullable=True))
        batch_op.create_index('idx_client_city', ['city'], unique=False)
        batch_op.create_index('idx_client_name', ['name'], unique=False)
        batch_op.create_index('idx_client_type', ['client_type'], unique=False)

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sun_exposure', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('moisture_level', sa.String(length=50), nullable=True))
        batch_op.create_index('idx_plant_category', ['category'], unique=False)
        batch_op.create_index('idx_plant_category_sun', ['category', 'sun_requirements'], unique=False)
        batch_op.create_index('idx_plant_hardiness_zone', ['hardiness_zone'], unique=False)
        batch_op.create_index('idx_plant_name', ['name'], unique=False)
        batch_op.create_index('idx_plant_native', ['native'], unique=False)
        batch_op.create_index('idx_plant_native_category', ['native', 'category'], unique=False)
        batch_op.create_index('idx_plant_price', ['price'], unique=False)
        batch_op.create_index('idx_plant_sun_requirements', ['sun_requirements'], unique=False)
        batch_op.create_index('idx_plant_supplier_id', ['supplier_id'], unique=False)
        batch_op.create_index('idx_plant_water_needs', ['water_needs'], unique=False)

    with op.batch_alter_table('project_plants', schema=None) as batch_op:
        batch_op.create_index('idx_project_plant_plant', ['plant_id'], unique=False)
        batch_op.create_index('idx_project_plant_project', ['project_id'], unique=False)
        batch_op.create_index('idx_project_plant_status', ['status'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('actual_completion_date', sa.Date(), nullable=True))
        batch_op.create_index('idx_project_budget', ['budget'], unique=False)
        batch_op.create_index('idx_project_client_id', ['client_id'], unique=False)
        batch_op.create_index('idx_project_project_type', ['project_type'], unique=False)
        batch_op.create_index('idx_project_start_date', ['start_date'], unique=False)
        batch_op.create_index('idx_project_status', ['status'], unique=False)
        batch_op.create_index('idx_project_status_client', ['status', 'client_id'], unique=False)
        batch_op.create_index('idx_project_type_status', ['project_type', 'status'], unique=False)

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_city', ['city'], unique=False)
        batch_op.create_index('idx_supplier_name', ['name'], unique=False)
        batch_op.create_index('idx_supplier_specialization', ['specialization'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index('idx_supplier_specialization')
        batch_op.drop_index('idx_supplier_name')
        batch_op.drop_index('idx_supplier_city')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_project_type_status')
        batch_op.drop_index('idx_project_status_client')
        batch_op.drop_index('idx_project_status')
        batch_op.drop_index('idx_project_start_date')
        batch_op.drop_index('idx_project_project_type')
        batch_op.drop_index('idx_project_client_id')
        batch_op.drop_index('idx_project_budget')
        batch_op.drop_column('actual_completion_date')
        batch_op.drop_column('target_completion_date')

    with op.batch_alter_table('project_plants', schema=None) as batch_op:
        batch_op.drop_index('idx_project_plant_status')
        batch_op.drop_index('idx_project_plant_project')
        batch_op.drop_index('idx_project_plant_plant')

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index('idx_plant_water_needs')
        batch_op.drop_index('idx_plant_supplier_id')
        batch_op.drop_index('idx_plant_sun_requirements')
        batch_op.drop_index('idx_plant_price')
        batch_op.drop_index('idx_plant_native_category')
        batch_op.drop_index('idx_plant_native')
        batch_op.drop_index('idx_plant_name')
        batch_op.drop_index('idx_plant_hardiness_zone')
        batch_op.drop_index('idx_plant_category_sun')
        batch_op.drop_index('idx_plant_category')
        batch_op.drop_column('moisture_level')
        batch_op.drop_column('sun_exposure')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('idx_client_type')
        batch_op.drop_index('idx_client_name')
        batch_op.drop_index('idx_client_city')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
